### ISSUE TITLE
Handling virtual cameras

### ISSUE THREAD

**Issue by unn** [wouterdebie/onair#2]
I have two apps that support virtual cameras mmhmm and OBS. Despite the applications not running the virtual cameras seem to be detected as in the "on" state. 

I'm not familiar enough with `AVFoundation` but it doesn't seem, in an obvious way, to be able to differentiate between a  physical device and a virtual one. Have any ideas?

**Comment by wouterdebie** [comment]
Interesting use case.. I have absolutely no idea how that works :) Currently I just call the camera's `isOn()` method, so I assume the virtual device will always return that it's on, even though the application that controls the camera device isn't running. Maybe a bug in those apps?

**Comment by unn** [comment]
It doesn't seem like an application bug, I pulled a few more virtual camera plugins and they all seem to exhibit this. Perhaps it's something in `AVFoundation` itself or `CoreMediaIO` DAL.

Example: https://github.com/johnboiles/coremediaio-dal-minimal-example

**Comment by wouterdebie** [comment]
Actually, I was wrong.. I implemented `isOn()` myself :) That said, I'm really not an expert in `AVFoundation` and probably found this on stackoverflow :) I'll do a bit more digging, since I don't really know how this works.

**Comment by unn** [comment]
Not a great solution, but a working one...

```
diff --git a/Sources/onair/Camera.swift b/Sources/onair/Camera.swift
index b1f28ec..16d63e3 100644
--- a/Sources/onair/Camera.swift
+++ b/Sources/onair/Camera.swift
@@ -32,6 +32,10 @@ class Camera: CustomStringConvertible {
     }

     func isOn() -> Bool {
+        if captureDevice.value(forKey: "_uniqueID") as! String == "obs-virtual-cam-device" {
+            return false
+        }
+
         // Test if the device is on through some magic. If the pointee is > 0, the device is active.
         var (dataSize, dataUsed) = (UInt32(0), UInt32(0))
         if CMIOObjectGetPropertyDataSize(id, &STATUS_PA, 0, nil, &dataSize) == OSStatus(kCMIOHardwareNoError) {
```

**Comment by wouterdebie** [comment]
But this doesn't give you the option to toggle virtual devices, right?

**Comment by unn** [comment]
No, but for my use-case, I will always be using a virtual camera with a physical hardware camera. In this case `onair` will still meet my needs since it's detecting that the hardware camera is 'on' while using the virtual camera to display the video to zoom, hangouts, skype, etc.

**Comment by wouterdebie** [comment]
I see what you mean. And it makes sense to only turn on a light if an actual hardware device is on and ignore any virtual devices. Do you know if there's a way to figure out if a device is virtual or not, apart from looking at the `_uniqueID`?

**Comment by unn** [comment]
That's what I was hoping you knew! 😄  

I tried debugging to see if there were some object property but nothing obvious jumped out.

**Comment by wouterdebie** [comment]
I'm updating my xcode right now, but could this be it? https://developer.apple.com/documentation/avfoundation/avcapturedevice/3153002-isvirtualdevice

**Comment by unn** [comment]
Not available for mac, just catalyst and ios unfortunately.

**Comment by wouterdebie** [comment]
:(

**Comment by wouterdebie** [comment]
I think I found something. It seems that DAL devices have a property `kCMIODevicePropertyLatency` set to 0 and regular `AVCaptureDevice` instances don't even have this property. I've implemented this on the `virtual_fix` branch and it seems to work. I installed OBS Studio to get a virtual device and it seems to ignore that now.

I do get a bunch of superfluous logging from the DAL device, but that's for another day :)

**Comment by wouterdebie** [comment]
I've tested this for half a day and it seems to work :)

**Comment by unn** [comment]
Working great here too. Thanks Wouter!

**Comment by ttimpe** [comment]
This does not seem to address the issue of DAL devices like Nikon's Webcam Utility or a Blackmagic capture card.

**Comment by wouterdebie** [comment]
@ttimpe Thanks for the feedback! I might just implement an ignore list, where you can specify what camera's you want to ignore on the command line, rather than trying to be clever.

**Comment by ttimpe** [comment]
Is there a way to find out if a DAL device is actually being used? Like an event for when the actual capture session starts? I have a similar project on the App Store to trigger HTTP requests for Homebridge and I'm using a Blackmagic Intensity Pro in conjunction with a DSLR going straight into video conferencing apps.

**Comment by wouterdebie** [comment]
It doesn't seem so unfortunately. As far as I know we have to use CoreIO
and the properties that are exposed by an AVCaptureDevice are somewhat
limited.. I don't have any contacts at Apple, but that would be super
helpful.

**Comment by wouterdebie** [comment]
I just pushed a commit that implements an ignore list, which solves this for `onair`. Obviously not for any other application, but I'm closing this issue for now.
